version: 2
updates:
  # npm packages
  - package-ecosystem: npm
    directory: /shade-agent-cli
    schedule:
      interval: monthly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /shade-agent-js
    schedule:
      interval: monthly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: npm
    directory: /shade-agent-template
    schedule:
      interval: monthly
    versioning-strategy: increase
    open-pull-requests-limit: 5

  # Rust crates
  - package-ecosystem: cargo
    directory: /shade-attestation
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: /shade-contract-template
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
