version: 2
updates:
  # npm packages
  - package-ecosystem: npm
    directory: /shade-agent-cli
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"

  - package-ecosystem: npm
    directory: /shade-agent-js
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"

  - package-ecosystem: npm
    directory: /shade-agent-template
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"

  # Rust crates
  - package-ecosystem: cargo
    directory: /shade-attestation
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"

  - package-ecosystem: cargo
    directory: /shade-contract-template
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
