services:
  shade-agent-app:
    environment:
      AGENT_CONTRACT_ID: ${AGENT_CONTRACT_ID}
      SPONSOR_ACCOUNT_ID: ${SPONSOR_ACCOUNT_ID}
      SPONSOR_PRIVATE_KEY: ${SPONSOR_PRIVATE_KEY}
    platform: linux/amd64
    image: pivortex/my-test-agent@sha256:d4e445ab9258038e5fa9cf2a751ae2aaf7aca0997729376b935532f9b4857bd3
    container_name: shade-agent-app
    ports:
      - 3000:3000
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
    restart: always
